# Generated by Django 3.2.4 on 2021-07-12 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='S_User',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(max_length=100, null=True, verbose_name='first name')),
                ('last_name', models.CharField(max_length=100, null=True, verbose_name='last name')),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('number', models.CharField(max_length=30, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
    ]
